name: Build staging AI-Platform NLP - pt_br-SPACY
on:
  push:
    tags:
      - 'staging-v*.*.*'
jobs:
  docker:
    runs-on: ubuntu-latest
    environment: 
      name: staging
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref: $environment
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: us.gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./aiplatform.Dockerfile
          push: true
          tags: us.gcr.io/bothub-273521/bothub-nlp-ai-platform:${{ steps.vars.outputs.tag }}-pt_br-SPACY
          no-cache: true
          build-args: |
            DOWNLOAD_MODELS=pt_br-SPACY
