name: Manual AI-Platform Build
on:
  workflow_dispatch:
    inputs:
      language_model:
        required: true
        default: 'pt_br-BERT'
        description: 'Language and model pattern'
      version:
        required: true
        description: 'Image version'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: us.gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./aiplatform.Dockerfile
          push: true
          tags: us.gcr.io/bothub-273521/bothub-nlp-ai-platform:${{ github.event.inputs.version }}-${{ github.event.inputs.language_model }}
          no-cache: true
          build-args: |
            DOWNLOAD_MODELS=${{ github.event.inputs.language_model }}