name: Build Develop Worker NLP - ga
on:
  push:
    tags:
      - 'develop-v*.*.*'
jobs:
  docker:
    runs-on: ubuntu-latest
    environment: 
      name: develop
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # START LOOP
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./nlp.Dockerfile
          push: true
          tags: bothubit/bothub-nlp:${{ steps.vars.outputs.tag }}-ga
          no-cache: true
          build-args: |
            DOWNLOAD_MODELS=ga:pip+ga_vectors_web_md:https://s3.amazonaws.com/bothub-models/spacy-2.1.9/ga_vectors_web_md-1.1.0.tar.gz
      # FINISH LOOP
