name: Build develop AI-Platform NLP - xx-SPACY
on:
  push:
    tags:
      - 'develop-v*.*.*'
jobs:
  docker:
    runs-on: ubuntu-latest
    environment: 
      name: develop
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./nlp.Dockerfile
          push: true
          tags: us.gcr.io/bothub-273521/bothub-nlp-ai-platform:${{ steps.vars.outputs.tag }}-xx-SPACY
          no-cache: true
          build-args: |
            DOWNLOAD_MODELS=xx-SPACY
